{
  "username": "Webhook",
  "avatar_url": "https://ibb.co/dbMs3hX",
  "content": "ahnnn ... quase infartei cupincha.",
  "embeds": [
    {
      "author": {
        "name": "Teste",
        "url": "https://www.reddit.com/r/cats/",
        "icon_url": "https://ibb.co/dbMs3hX"
      },
      "title": "Title",
      "url": "https://google.com/",
      "description": "Text message. You can use Markdown here. *Italic* **bold** __underline__ ~~strikeout~~ [hyperlink](https://google.com) `code`",
      "color": 15258703,
      "fields": [
        {
          "name": "Text",
          "value": "More text",
          "inline": true
        },
        {
          "name": "Even more text",
          "value": "Yup",
          "inline": true
        },
        {
          "name": "Use `\"inline\": true` parameter, if you want to display fields in the same line.",
          "value": "okay..."
        },
        {
          "name": "Thanks!",
          "value": "You're welcome :wink:"
        }
      ],
      "thumbnail": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/3/38/4-Nature-Wallpapers-2014-1_ukaavUI.jpg"
      },
      "image": {
        "url": "https://instagram.fplu19-1.fna.fbcdn.net/v/t51.2885-15/e35/210225360_3002805683373785_448500043474140247_n.jpg?_n"
      },
      "footer": {
        "text": "Woah! So cool! :smirk:",
        "icon_url": "https://ibb.co/dbMs3hX"
      }
    }
  ]
}
